[project]
name = "neo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "graphrag>=2.0.0",
    "neo4j-graphrag>=1.5.0",
    "plotly>=6.0.1",
    "pyvis>=0.3.2",
    "tqdm>=4.67.1",
]
